import express from 'express';
import http from 'http';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { WebSocketServer, WebSocket } from 'ws';
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,path:'/events'});
const PORT=Number(process.env.PORT||3000),PASS=String(process.env.ADMIN_PASSWORD||''),PROD=process.env.NODE_ENV==='production';
const DATA_DIR=process.env.DATA_DIR||path.join(process.cwd(),'data'),STATE_FILE=path.join(DATA_DIR,'state.json');
app.use(express.json({limit:'18mb'}));app.use(express.static('.', {index:'index.html'}));
const FONT_IDS=['Bangers','Luckiest Guy','Bowlby One SC','Black Ops One','Russo One','Titan One','Anton','Lilita One'];
function defaults(){return{battle:{title:'BATALHA DAS OPÇÕES',subtitle:'Envie presentes para a sua opção favorita!',backgroundImage:'',titleFont:'Bangers',titleSize:40},timer:{elapsedMs:0,running:false,startedAt:null},options:[{id:crypto.randomUUID(),name:'Opção A',image:'',giftIcon:'',color:'#ffcc00',gifts:'Rosa, Coração',count:0},{id:crypto.randomUUID(),name:'Opção B',image:'',giftIcon:'',color:'#9aa7b3',gifts:'Café, Perfume',count:0}],lastGift:null}}
function load(){try{const saved=JSON.parse(fs.readFileSync(STATE_FILE,'utf8')),d=defaults();return{...d,...saved,battle:{...d.battle,...(saved.battle||{})},timer:{...d.timer,...(saved.timer||{})}}}catch{return defaults()}}let state=load();
function persist(){try{fs.mkdirSync(DATA_DIR,{recursive:true});fs.writeFileSync(STATE_FILE,JSON.stringify(state),'utf8')}catch(e){console.error('Não foi possível persistir estado:',e.message)}}
function auth(req,res,next){if(!PASS&&!PROD)return next();if(!PASS)return res.status(503).send('ADMIN_PASSWORD não configurada');const h=req.headers.authorization||'';if(!h.startsWith('Basic ')){res.set('WWW-Authenticate','Basic realm="Batalha Admin"');return res.status(401).end()}try{const d=Buffer.from(h.slice(6),'base64').toString(),i=d.indexOf(':'),u=d.slice(0,i),p=d.slice(i+1),a=Buffer.from(p),b=Buffer.from(PASS);if(u==='admin'&&a.length===b.length&&crypto.timingSafeEqual(a,b))return next()}catch{}res.set('WWW-Authenticate','Basic realm="Batalha Admin"');res.status(401).end()}
function send(type,payload={}){const msg=JSON.stringify({type,...payload,at:Date.now()});for(const ws of wss.clients)if(ws.readyState===WebSocket.OPEN)ws.send(msg)}function norm(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase()}function giftNames(s=''){return String(s).split(',').map(norm).filter(Boolean)}
function cleanOption(o={}){return{id:String(o.id||crypto.randomUUID()),name:String(o.name||'Opção').trim().slice(0,80),image:String(o.image||'').slice(0,7500000),giftIcon:String(o.giftIcon||'').slice(0,3000000),color:/^#[0-9a-f]{6}$/i.test(String(o.color||''))?String(o.color):'#2f7cff',gifts:String(o.gifts||'').trim().slice(0,1500),count:Math.max(0,Number(o.count)||0)}}
function cleanBattle(b={}){const f=FONT_IDS.includes(String(b.titleFont))?String(b.titleFont):'Bangers',sz=Math.max(24,Math.min(48,Number(b.titleSize)||40));return{title:String(b.title||'BATALHA DAS OPÇÕES').trim().slice(0,100),subtitle:String(b.subtitle||'Envie presentes para a sua opção favorita!').trim().slice(0,180),backgroundImage:String(b.backgroundImage||'').slice(0,8000000),titleFont:f,titleSize:sz}}
function timerSnapshot(){return{elapsedMs:state.timer.elapsedMs+(state.timer.running&&state.timer.startedAt?Date.now()-state.timer.startedAt:0),running:state.timer.running,startedAt:state.timer.startedAt}}
function registerGift(data={}){const giftName=String(data.giftName||'').trim();if(!giftName)return{matched:false};const n=norm(giftName),opt=state.options.find(o=>giftNames(o.gifts).includes(n));if(!opt)return{matched:false,giftName};const repeat=Math.max(1,Number(data.repeatCount||1));opt.count+=repeat;state.lastGift={optionId:opt.id,optionName:opt.name,giftName,repeatCount:repeat,user:data.user||null,at:Date.now()};persist();send('gift',{options:state.options,battle:state.battle,timer:timerSnapshot()});return{matched:true,option:opt}}
app.get('/api/health',(req,res)=>res.json({ok:true,version:6}));app.get('/api/state',(req,res)=>res.json({...state,timer:timerSnapshot()}));app.post('/api/relay',auth,(req,res)=>{if(String(req.body?.event||'')!=='gift')return res.status(400).json({ok:false,error:'Somente evento gift é aceito'});res.json({ok:true,...registerGift(req.body?.data||{})})});app.post('/api/config',auth,(req,res)=>{const options=Array.isArray(req.body?.options)?req.body.options:[];if(!options.length)return res.status(400).json({ok:false,error:'Crie pelo menos uma opção'});state.battle=cleanBattle(req.body?.battle||{});state.options=options.slice(0,6).map(cleanOption);persist();send('state',{...state,timer:timerSnapshot()});res.json({ok:true,...state,timer:timerSnapshot()})});app.post('/api/reset',auth,(req,res)=>{for(const o of state.options)o.count=0;state.lastGift=null;persist();send('state',{...state,timer:timerSnapshot()});res.json({ok:true})});app.post('/api/reset-all',auth,(req,res)=>{state=defaults();persist();send('state',{...state,timer:timerSnapshot()});res.json({ok:true,...state,timer:timerSnapshot()})});app.post('/api/manual',auth,(req,res)=>{const id=String(req.body?.id||''),amount=Math.max(1,Math.min(999,Number(req.body?.amount||1))),opt=state.options.find(o=>o.id===id);if(!opt)return res.status(404).json({ok:false,error:'Opção não encontrada'});opt.count+=amount;persist();send('state',{...state,timer:timerSnapshot()});res.json({ok:true})});
app.post('/api/timer',auth,(req,res)=>{const action=String(req.body?.action||'');if(action==='play'){if(!state.timer.running){state.timer.running=true;state.timer.startedAt=Date.now()}}else if(action==='pause'){if(state.timer.running&&state.timer.startedAt)state.timer.elapsedMs+=Date.now()-state.timer.startedAt;state.timer.running=false;state.timer.startedAt=null}else if(action==='reset'){state.timer.elapsedMs=0;state.timer.running=false;state.timer.startedAt=null}else return res.status(400).json({ok:false,error:'Ação inválida'});persist();const timer=timerSnapshot();send('timer',{timer});res.json({ok:true,timer})});
app.post('/api/champion',auth,(req,res)=>{if(!state.options.length)return res.status(400).json({ok:false,error:'Sem opções'});const max=Math.max(...state.options.map(o=>Number(o.count)||0)),leaders=state.options.filter(o=>(Number(o.count)||0)===max);if(max<=0)return res.status(400).json({ok:false,error:'Ainda não há pontos'});if(leaders.length!==1)return res.status(400).json({ok:false,error:'Há empate no primeiro lugar'});const champion=leaders[0];send('champion',{champion});res.json({ok:true,champion})});
app.get(['/admin','/admin.html'],auth,(req,res)=>res.sendFile(new URL('./admin.html',import.meta.url).pathname));wss.on('connection',ws=>ws.send(JSON.stringify({type:'state',...state,timer:timerSnapshot()})));server.listen(PORT,'0.0.0.0',()=>console.log(`Batalha de Opções rodando na porta ${PORT}`));